### ISSUE TITLE
How to use files?

### ISSUE THREAD

**Issue by mohkale** [nemethf/eglot-x#10]
Hi there,

Is there any examples or documentation on how to run the files feature? I might've misunderstood but I had thought it would allow something like running a language server in docker while emacs itself runs on a local machine but it's not clear how to support that.

**Comment by nemethf** [comment]
It is possible to have the source code on one computer, the language server on another, and emacs on yet another computer.  However, the server must support the "files" extension.  In practice, this setup is only usable if the project is small.

I haven't used this extension recently, but it the past I started the server manually to listen on a given port, then I opened a source file and gave the address:port combo after C-u M-x eglot RET.   I also used ssh port forwarding to encrypt the LSP communication.

The only LSP server I know that directly supports the "files" extension is an old [php server](https://github.com/felixfbecker/php-language-server).  However, most servers can be enhanced to support the extension with the [lsp-adapter](https://github.com/sourcegraph/lsp-adapter).  The lsp-adapter is discontinued, which shows the "files" extension haven't gained traction.

---

If the language server is running inside a local docker container, then Eglot (without eglot-x) can be used.  I think the easiest way is to share the source directory between the container and the host system and use tramp to open the source files inside the running container.

Running the server inside a container is useful when the installation process is complicated.  However, it is less useful if the server is not trustworthy.  The server won't be able to directly run malicious code on the host machine, but it can inject malicious code into the project's source code or its build system.

**Comment by mohkale** [comment]
I see, so you have to basically replicate the source directory and remote directory layout on both hosts. There's no way to configure remapping so container says path is /workarea/src/x/y/z and eglot will translate to MY_LOCAL_SOURCE_DIR/src/x/y/z :thinking:. 

The general lack of support is a bit disappointing :cry:. I was hoping to use this with clangd based projects. Going to go ahead and close.

**Comment by nemethf** [comment]
> I see, so you have to basically replicate the source directory and remote directory layout on both hosts. There's no way to configure remapping so container says path is /workarea/src/x/y/z and eglot will translate to MY_LOCAL_SOURCE_DIR/src/x/y/z 🤔.

No.  If you use the "files" extension of eglot-x, then the server will request the files it needs from the LSP client, no prior setup is necessary.  On the other hand, if you use eglot without the "files" extension, the files should be on the server's file system and emacs should open them with tramp.

**Comment by mohkale** [comment]
This is still confusing to me tho. If I mount them at different locations the language server and my client need to agree on a remapping scheme for them right. Do you have any example projects or setups actually demonstrating how to do this?

**Comment by nemethf** [comment]
Which case are you talking about?  The one that needs just eglot or other one that needs the files extension implemented in eglot-x?
