### ISSUE TITLE
Bug report: recent commit of `eglot-x` breaks `xref-go-back`

### ISSUE THREAD

**Issue by roife** [nemethf/eglot-x#11]
Hi! Thank you for your contributions to this project. This package has greatly helped me in debugging `rust-analyzer` on Emacs.

However, recently I encountered an issue after from the commit `a7994d19f4f98ba8d943ee4c55c5082ec2d8b82f` where Emacs frequently reports the following error:

```
eglot-x--run-after-jump: [eglot-x] Server sent an unknown Runnable kind: nil
```

This error makes `xref-go-back` unusable. I suspect it might be a bug in `eglot-x`. Could you please look into it?

**Comment by nemethf** [comment]
The report does not say how the issue can be reproduced, so it is hard to understand the underlying problem, but I fixed something.
