### ISSUE TITLE
eglot-x-expand-macro unconditionally calls rust-mode

### ISSUE THREAD

**Issue by gessen** [nemethf/eglot-x#15]
`eglot-x-expand-macro` will always call `rust-mode` but it is possible that a user doesn't have it and uses built-in `rust-ts-mode`. Would it be possible to modify it with something like:
```diff
-    (rust-mode)
+    (if (fboundp 'rust-mode)
+        (rust-mode)
+      (rust-ts-mode))
```

**Comment by nemethf** [comment]
Hopefully, this is now fixed.  However, is this command really useful? I find it annoying that the expansion buffer is not manged by the lsp server, e.g., `M-.` does not work there.  And I have no idea how the UI could be improved.

**Comment by gessen** [comment]
It's fixed, thanks a lot. I sometimes use this command when I develop new macro so it's useful at least for 1 person :)
