### ISSUE TITLE
eglot 1.16

### ISSUE THREAD

**Issue by yrns** [nemethf/eglot-x#8]
I just updated to eglot 1.16 and noticed a parameter was added to `eglot--apply-text-edits`:

https://github.com/joaotavora/eglot/commit/88c46bd4dbaa82b4af46aed9b578b121f0edfe48#diff-d6c5a55ddb4dd8dca075c4e0d48c851460ead14c77f333c66b02ccc7d1c2aff0L3320

This results in errors with the advised version:

`Before-save hook error: (wrong-number-of-arguments #<subr eglot-x--apply-text-edits> 3)`

**Comment by nemethf** [comment]
I wasn't able to reproduce this, I pushed a commit that hopefully fixes it.  Thanks.

**Comment by PuercoPop** [comment]
@nemethf It fixed the issue for me. Thanks! Would it be possible to bump the version? It would make it easier to update the version in Guix, where they tried to package only released versions
